name: gtfs_pb
description: Package to handle with GTFS-RT .pb (Protocol Buffers) files
version: 0.0.1
homepage: https://github.com/Zabior/gtfs_pb

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

