name: gtfs_pb
description: Package to handle with GTFS-RT .pb (Protocol Buffers) files
version: 0.0.2-nullsafety.0
homepage: https://github.com/Zabior/gtfs_pb

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  protobuf: ^2.0.0-nullsafety.0
